// src/components/GameEntry.tsx
import {
  Box,
  Fab,
  ListItemIcon,
  Menu,
  MenuItem,
  styled,
  Typography,
} from "@mui/material";
import {
  FunctionComponent,
  MouseEvent,
  MouseEventHandler,
  useMemo,
  useState,
} from "react";
import { useLibrary } from "../hooks/useLibrary";
import { useSyncService } from "../hooks/useSyncService";
import Icon from "@mdi/react";
import {
  mdiBackupRestore,
  mdiChevronDoubleRight,
  mdiClose,
  mdiDelete,
  mdiDotsHorizontal,
  mdiDownload,
  mdiFolderOpen,
  mdiPause,
  mdiPlay,
} from "@mdi/js";
import { useTranslation } from "react-i18next";
import { useGameFolder } from "../hooks/useGameFolder";

const hoverAnimation = "0.2s ease-in-out";

interface GameEntryRootProps {
  installed: boolean;
}

const GameEntryRoot = styled("div")<GameEntryRootProps>(
  ({ theme, installed }) => ({
    position: "relative",
    width: "190px",
    overflow: "hidden",
    margin: theme.spacing(1.5),
    // Game image styling
    img: {
      width: "100%",
      height: "auto",
    },
    // Every child element that is not the game thumbnail is absolutely positioned => stacked on each other
    "& > *:not(img)": {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
    },
    ...(installed
      ? {
          transition: `transform ${hoverAnimation}`,
          cursor: "pointer",
          "&:hover": {
            transform: "perspective(10px) rotateX(0.1deg)",
            ".glass": {
              top: "-70% !important",
            },
          },
        }
      : {}),
  })
);

interface ProgressIndicatorProps {
  downloadProgress: number;
}

const ProgressIndicator = styled("div")<ProgressIndicatorProps>(
  ({ downloadProgress }) => ({
    top: `${-downloadProgress * 100}%`,
  })
);

const DownloadButtonsContainer = styled("div")(() => ({
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
}));

const Glass = styled("div")(() => ({
  transition: `top ${hoverAnimation}`,
  top: "-175% !important",
  height: "200% !important",
  width: "200% !important",
  boxShadow: "0px 0px 20px 5px white, inset 0px 0px 20px 5px white",
  transform: "rotate(-45deg)",
}));

interface GameEntryProps {
  gameConfig: Game;
}

export const GameEntry: FunctionComponent<GameEntryProps> = ({
  gameConfig,
}) => {
  /* -------------------------------------------------------------------------- */
  /*                                   Context                                  */
  /* -------------------------------------------------------------------------- */
  const { libFolderPath } = useLibrary();
  const { t } = useTranslation();

  /* -------------------------------------------------------------------------- */
  /*                                    State                                   */
  /* -------------------------------------------------------------------------- */
  const [thisGameFolder, thisGameFolderStatus] = useGameFolder(gameConfig);
  const subscribed = useMemo(() => !!thisGameFolder, [thisGameFolder]);
  const downloadProgress = useMemo(
    () =>
      subscribed && thisGameFolderStatus?.globalBytes > 0
        ? thisGameFolderStatus?.inSyncBytes / thisGameFolderStatus?.globalBytes
        : 0,
    []
  );
  const installed = useMemo(() => downloadProgress >= 1, [downloadProgress]);

  const downloadButtons = useMemo(
    () => [
      { click: () => download, show: !subscribed, icon: mdiDownload },
      { click: () => pause, show: thisGameFolder?.paused, icon: mdiPause },
      {
        click: () => resume,
        show: thisGameFolder?.paused,
        icon: mdiChevronDoubleRight,
      },
      { click: () => remove, show: subscribed, icon: mdiClose },
    ],
    [subscribed, thisGameFolder]
  );

  const gameMenuButtons = useMemo(
    () => [
      {
        click: () => execute,
        show: true,
        icon: mdiPlay,
        text: t("gameEntry.play"),
      },
      ...(gameConfig.moreLaunchs || []).map((item) => ({
        click: () => execute,
        show: true,
        icon: mdiDotsHorizontal,
        text: item.text,
      })),
      {
        click: () => pause,
        show: thisGameFolder?.paused,
        icon: mdiPause,
        text: t("gameEntry.pause"),
      },
      {
        click: () => resume,
        show: thisGameFolder?.paused,
        icon: mdiChevronDoubleRight,
        text: t("gameEntry.resume"),
      },
      {
        click: () => reset,
        show: thisGameFolderStatus?.receiveOnlyTotalItems > 0,
        icon: mdiBackupRestore,
        text: t("gameEntry.reset"),
      },
      {
        click: () => browse,
        show: true,
        icon: mdiFolderOpen,
        text: t("gameEntry.browse"),
      },
      {
        click: () => remove,
        show: true,
        icon: mdiDelete,
        text: t("gameEntry.delete"),
      },
    ],
    [thisGameFolder, thisGameFolderStatus, t]
  );

  const [anchorEl, setAnchorEl] = useState(null);

  /* -------------------------------------------------------------------------- */
  /*                             Instance functions                             */
  /* -------------------------------------------------------------------------- */
  const download = () => {};
  const pause = () => {};
  const resume = () => {};
  const remove = () => {};
  const execute = () => {};
  const reset = () => {};
  const browse = () => {};

  const handleMenuOpenClick = (event: MouseEvent<HTMLDivElement>) => {
    setAnchorEl(event.currentTarget);
  };
  const handleMenuClose = () => {
    setAnchorEl(null);
  };

  /* -------------------------------------------------------------------------- */
  /*                                  Rendering                                 */
  /* -------------------------------------------------------------------------- */
  return (
    <>
      <GameEntryRoot installed={installed} onClick={handleMenuOpenClick}>
        {/* Game Thumbnail */}
        <img src={`game://${libFolderPath}/${gameConfig.cover}`} />
        {/* Progress indicator */}
        <ProgressIndicator downloadProgress={downloadProgress} />
        {/* Download buttons overlay. Only displayed when downloadProgress < 1, hence not completed */}
        {downloadProgress < 1 ? (
          <DownloadButtonsContainer>
            {subscribed && Object.keys(thisGameFolderStatus).length === 0 ? (
              // If game is subscribed but there is no syncFolderStatus yet, show loader
              <Fab></Fab>
            ) : (
              // Else show applicable download buttons
              downloadButtons.map(
                ({ click, show, icon }, index) =>
                  show && (
                    <Box key={index} m={0.5}>
                      <Fab onClick={click}>
                        <Icon path={icon} size={1.5} />
                      </Fab>
                    </Box>
                  )
              )
            )}
          </DownloadButtonsContainer>
        ) : (
          <Glass className="glass" />
        )}
      </GameEntryRoot>

      {/* Game Menu */}
      <Menu
        anchorEl={anchorEl}
        open={!!anchorEl}
        onClose={handleMenuClose}
        anchorOrigin={{
          vertical: "top",
          horizontal: "right",
        }}
        transformOrigin={{
          vertical: "top",
          horizontal: "left",
        }}
      >
        {gameMenuButtons.map(
          ({ click, show, icon, text }, index) =>
            show && (
              <MenuItem key={index} onClick={click}>
                <ListItemIcon>
                  <Icon path={icon} size={1} />
                </ListItemIcon>
                <Typography mx={1}>{text}</Typography>
              </MenuItem>
            )
        )}
      </Menu>
    </>
  );
};

// src/components/GameEntry.vue
<style lang="scss" scoped>
$hover-animation: 0.2s ease-in-out;

.gameEntry {
  width: 190px;
  position: relative;
  overflow: hidden;

  &.installed {
    transition: transform $hover-animation;
    cursor: pointer;

    // Game entry hover effect adjustments
    &:hover {
      transform: perspective(10px) rotateX(0.1deg);

      // Glass hover effect adjustments
      .glass {
        top: -70%;
      }
    }
  }

  // Game thumbnail styling
  &::v-deep img {
    width: 100%;
    height: auto;
  }

  // Every child element that is not the game thumbnail is absolutely positioned => stacked on each other
  & > :not(.v-image) {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

  // Download progress styling
  .progress {
    background: rgba(0, 0, 0, 0.7);
    transition: top 0.1s linear;
  }

  // Glass effect base styling
  .glass {
    transition: top $hover-animation;
    top: -175%;
    height: 200%;
    width: 200%;
    box-shadow: 0px 0px 20px 5px white, inset 0px 0px 20px 5px white;
    transform: rotate(-45deg);
  }
}
</style>

<template>
  <v-menu
    offset-x
    open-on-click
    transition="slide-x-transition"
  >
    <template v-slot:activator="{ on }">
      <div
        class="gameEntry ma-3"
        :class="downloadProgress >= 1 ? 'installed' : ''"
      >
        <v-img
          :src="`game://${homeDir}/${require('../config/folder').gamelibDirName}/${value.cover}`"
          :aspect-ratio="600/900"
          eager
        />
        <!-- Progress indicator -->
        <div
          class="progress"
          :style="{top: `${-downloadProgress*100}%`}"
        ></div>
        <!-- Download buttons overlay. Only displayed when downloadProgress < 1, hence not completed -->
        <div
          class="download d-flex flex-column justify-center align-center"
          v-if="downloadProgress < 1"
        >
          <!-- If game is subscribed but there is no status yet, show loader -->
          <v-btn
            fab
            x-large
            @click="$emit('download')"
            v-if="subscribed && Object.keys(status).length == 0"
            loading
          />
          <!-- Else show applicable download buttons -->
          <template v-else>
            <template v-for="(item, index) in downloadButtons">
              <v-btn
                fab
                x-large
                @click="item.click"
                v-if="item.show"
                :key="index"
              >
                <v-icon>{{item.icon}}</v-icon>
              </v-btn>
            </template>
          </template>
        </div>
        <div
          v-else
          class="glass"
          v-on="on"
        >
        </div>
      </div>
    </template>

    <!-- Game menu -->
    <v-card>
      <div class="d-flex flex-column">
        <template v-for="(item, index) in gameMenuButtons">
          <v-btn
            text
            block
            @click="item.click"
            v-if="item.show"
            class="justify-start"
            :key="index"
          >
            <v-icon left>{{item.icon}}</v-icon>{{item.text}}
          </v-btn>
        </template>
      </div>
    </v-card>
  </v-menu>
</template>

<script>
export default {
  props: {
    value: Object,
    homeDir: String,
    config: Object,
    status: Object,
  },
  computed: {
    subscribed() {
      return this.config != null;
    },
    downloadProgress() {
      return this.subscribed && this.status.globalBytes > 0
        ? this.status.inSyncBytes / this.status.globalBytes
        : 0;
    },
    downloadButtons() {
      return [
        {
          click: () => this.$emit("download"),
          show: !this.subscribed,
          icon: "mdi-download",
        },
        {
          click: () => this.$emit("pause"),
          show: this.config && !this.config.paused,
          icon: "mdi-pause",
        },
        {
          click: () => this.$emit("resume"),
          show: this.config && this.config.paused,
          icon: "mdi-chevron-double-right",
        },
        {
          click: () => this.$emit("delete"),
          show: this.subscribed,
          icon: "mdi-close",
        },
      ];
    },
    gameMenuButtons() {
      let buttons = [
        {
          click: () =>
            this.$emit("execute", this.config, this.value, this.value.launch),
          show: true,
          icon: "mdi-play",
          text: this.$t("gameEntry.play"),
        },
        {
          click: () => this.$emit("pause"),
          show: this.config && !this.config.paused,
          icon: "mdi-pause",
          text: this.$t("gameEntry.pause"),
        },
        {
          click: () => this.$emit("resume"),
          show: this.config && this.config.paused,
          icon: "mdi-chevron-double-right",
          text: this.$t("gameEntry.resume"),
        },
        {
          click: () => this.$emit("reset"),
          show: this.status.receiveOnlyTotalItems > 0,
          icon: "mdi-backup-restore",
          text: this.$t("gameEntry.reset"),
        },
        {
          click: () => this.$emit("browse"),
          show: true,
          icon: "mdi-folder-open",
          text: this.$t("gameEntry.browse"),
        },
        {
          click: () => this.$emit("delete"),
          show: true,
          icon: "mdi-delete",
          text: this.$t("gameEntry.delete"),
        },
      ];

      (this.value.moreLaunchs || []).forEach((item) => {
        buttons.splice(-2, 0, {
          click: () => this.$emit("execute", item),
          show: true,
          icon: "mdi-dots-horizontal",
          text: item.text,
        });
      });

      return buttons;
    },
  },
};
</script>
