// src/components/SettingsView.vue
<template>
  <v-container>
    <v-alert type="error" variant="tonal" border="start" class="my-1" :title="$t('errors.playerNameUnset.title')"
      v-if="playerName == false">
      {{ $t("errors.playerNameUnset.message") }}
    </v-alert>
    <v-alert type="error" variant="tonal" border="start" class="my-1" :title="$t('errors.homeDirUnset.title')"
      v-if="homeDir == false">
      {{ $t("errors.homeDirUnset.message") }}
    </v-alert>
    <v-alert type="error" variant="tonal" border="start" class="my-1" :title="$t('errors.nasUnset.title')"
      v-if="nas == false">
      {{ $t("errors.nasUnset.message") }}
    </v-alert>
    <div class="text-h4">{{ $t("settings.theme") }}</div>
    <div class="d-flex mx-n3 flex-wrap">
      <v-img v-for="(item, index) in textures" :key="index" class="themePreview ma-3" aspect-ratio="1" :src="item"
        @click.native="() => {
          store.commit(StoreAttributes.THEME, { path: item, cover: false });
        }
          " eager></v-img>
      <div class="themePreview ma-3 bg-transparent-dark align-center justify-center"
        :style="{ border: `1px solid hsl(${backgroundHue}, 100%, 35%)` }" @click="
          openFileChooser(
            (result) =>
              store.commit(StoreAttributes.THEME, {
                path: `theme://${result.filePaths[0].replace(/\\/g, '/')}`,
                cover: true,
              }),
            {
              properties: ['openFile'],
              filters: [
                {
                  name: $t('settings.images'),
                  extensions: ['jpg', 'jpeg', 'png'],
                },
              ],
            }
          )
          ">
        <span style="padding-bottom: 100%"></span>
        <v-icon x-large :icon="mdiImageSearch" />
      </div>
    </div>

    <div class="mt-5 text-h4">{{ $t("settings.backgroundHue") }}</div>
    <v-row>
      <v-col cols="12">
        <v-slider :min="0" :max="360" thumb-label v-model="sliderValue" :color="'hsl(' + sliderValue + ', 100%, 50%)'"
          @change="(input) => {
            store.commit(StoreAttributes.BACKGROUND_HUE, input);
          }
            " />
      </v-col>
    </v-row>

    <div class="text-h4">{{ $t("settings.environment") }}</div>
    <v-row>
      <v-col cols="3">
        <v-select :label="$t('settings.language')" v-model="locale" :items="langs"
          :item-title="(lang) => $t(`langs.${lang}`)" :item-value="(lang) => lang" />
      </v-col>
      <v-col cols="5" class="offset-4">
        <v-tooltip top max-width="400">
          <template v-slot:activator="{ on }">
            <v-switch v-model="debug">
              <template v-slot:label>
                <span v-on="on">{{ $t('settings.debug') }}</span>
              </template>
            </v-switch>
          </template>
          <span v-html="$t('settings.debug_explanation')"></span>
        </v-tooltip>
      </v-col>
    </v-row>
    <v-row>
      <v-col cols="3">
        <v-text-field :label="$t('settings.playerName')" :value="playerName" @blur="(event) => {
          store.commit(StoreAttributes.PLAYER_NAME, event.target.value);
        }
          " :error="playerName == false" />
      </v-col>
      <v-col cols="4">
        <div class="d-flex align-baseline">
          <v-text-field :label="$t('settings.homeDir')" @click="setHomeDir" :readonly="true" :value="homeDir"
            :disabled="online" :error="homeDir == false" class="mr-2" />
          <v-btn @click="setHomeDir" :disabled="online" color="primary">{{ $t('settings.chooseHomeDir') }}</v-btn>
        </div>
      </v-col>
      <v-col cols="5">
        <v-select :disabled="!online" :label="$t('settings.nas')" :value="nas" :items="Object.entries(devices)"
          :item-value="(device) => device[0]" :item-text="(device) => device[0]" :error="nas == false"
          @change="(input) => store.commit(StoreAttributes.NAS, input)" :no-data-text="$t('settings.alerts.discovery')"
          :error-messages="!online ? $t('settings.alerts.service') : null" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { mdiImageSearch } from "@mdi/js";

import SyncServiceController from "../controllers/SyncServiceRendererController";
import { ref, onBeforeMount, onUnmounted, watchEffect } from "vue";
import { default as _langs } from "../localization/langs";
import { useStore } from "vuex";
import { useComputedStoreAttribute } from '../composables/useComputedStoreAttribute';
import { StoreAttributes } from "../plugins/store";

let discoveryInterval: ReturnType<typeof setTimeout>;

const { online } = defineProps(['online']);

const textures = [
  "./funky-lines.png",
  "./gaming.png",
  "./prism.png",
  "./maze.png",
  "./unicorns.png",
];

const store = useStore();
const { playerName, homeDir, nas, backgroundHue } = store.state;

const sliderValue = ref(backgroundHue);
const devices = ref([]);
const langs = Object.keys(_langs);

const locale = useComputedStoreAttribute(StoreAttributes.LOCALE);
const debug = useComputedStoreAttribute(StoreAttributes.DEBUG);

onBeforeMount(() => {
  discoveryTask();
  clearInterval(discoveryInterval);
  if (online.value) {
    discoveryInterval = setInterval(discoveryTask, 5000);
  }
});

onUnmounted(() => {
  clearInterval(discoveryInterval);
})

watchEffect(() => {
  if (online) {
    discoveryInterval = setInterval(discoveryTask, 5000);
  } else {
    clearInterval(discoveryInterval);
  }
});

watchEffect(() => {
  if (online && !!homeDir) {
    SyncServiceController.System.start(homeDir);
  }
});

/**
 * Open the electron file-chooser-dialog with the specified options.
 * @param {Function} callback The function to call when a file was picked.
 * @param {Object} options The options object for the electron file chooser.
 */
function openFileChooser(callback: (result: any) => void, options: any) {
  window.ipcRenderer.invoke("showOpenDialog", options).then((result) => {
    if (!result.canceled) callback(result);
  });
}

function setHomeDir() {
  openFileChooser(
    (result) => {
      store.commit(StoreAttributes.HOME_DIR, result.filePaths[0]);
    },
    { properties: ['openDirectory'] }
  )
}

/**
 * Periodic task to fetch discovered Syncthing devices.
 */
function discoveryTask() {
  SyncServiceController.System.getDiscovery()
    .then((response) => {
      devices.value = response.data;
    })
    .catch();
}
</script>

<style lang="scss" scoped>
.themePreview {
  border-radius: 10px;
  cursor: pointer;
  display: flex;
  width: 200px;
  max-width: 200px;
  transition: transform 0.1s ease-in-out;

  &:hover {
    transform: scale(1.1);
  }
}
</style>

// src/components/SettingsView.tsx
import { mdiDatabaseSearch, mdiImageSearch } from "@mdi/js";
import Icon from "@mdi/react";
import {
  Alert,
  Box,
  Button,
  Container,
  FormControl,
  FormControlLabel,
  FormHelperText,
  Grid,
  InputLabel,
  MenuItem,
  Select,
  Slider,
  styled,
  Switch,
  TextField,
  Theme,
  Tooltip,
} from "@mui/material";
import { FunctionComponent, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { bgTransparentDarkWithBlur } from "../App";
import { useFileChooser } from "../hooks/useFileChooser";
import { useSettingsService } from "../hooks/useSettingsService";
import { useSyncService } from "../hooks/useSyncService";
import langs from "../localization/langs";

const ThemeItem = ({ theme }: { theme: Theme }) => ({
  margin: theme.spacing(3),
  borderRadius: 10,
  cursor: "pointer",
  display: "flex",
  height: 200,
  maxHeight: 200,
  width: 200,
  maxWidth: 200,
  transition: "transform 0.1s ease-in-out",

  ":hover": {
    transform: "scale(1.1)",
  },
});

const PredefinedThemeItem = styled("img")(ThemeItem);

interface CustomBackgroundPickerProps {
  hue: number;
}
const CustomBackgroundPicker = styled("div")<CustomBackgroundPickerProps>(
  ({ hue: hue, theme }) => ({
    ...ThemeItem({ theme }),
    ...bgTransparentDarkWithBlur,
    border: `1px solid hsl(${hue}, 100%, 35%)`,
    alignItems: "center",
    justifyContent: "center",
  })
);

export const SettingsView: FunctionComponent = () => {
  /* -------------------------------------------------------------------------- */
  /*                                   Context                                  */
  /* -------------------------------------------------------------------------- */
  const { t } = useTranslation();
  const {
    playerName,
    homeDir,
    nas,
    backgroundHue,
    locale,
    debug,
    setTheme,
    setBackgroundHue,
    setLocale,
    setDebug,
    setPlayerName,
    setHomeDir,
    setNas,
  } = useSettingsService();
  const { started, online, getDiscovery } = useSyncService();
  const { openFileChooser } = useFileChooser();

  /* -------------------------------------------------------------------------- */
  /*                                    State                                   */
  /* -------------------------------------------------------------------------- */
  const [devices, setDevices] = useState({});

  /* -------------------------------------------------------------------------- */
  /*                             Instance Lifecycle                             */
  /* -------------------------------------------------------------------------- */
  useEffect(() => {
    async function discoveryTask() {
      try {
        const response = await getDiscovery();
        setDevices(response.data);
      } catch (e) {
        // Do nothing
      }
    }
    let discoveryInterval: ReturnType<typeof setInterval>;
    if (online) {
      discoveryInterval = setInterval(discoveryTask, 1000);
    }
    return () => discoveryInterval && clearInterval(discoveryInterval);
  }, [online]);

  /* -------------------------------------------------------------------------- */
  /*                             Instance Functions                             */
  /* -------------------------------------------------------------------------- */
  function selectCustomBackground() {
    openFileChooser(
      (result) => {
        setTheme({
          path: `theme://${result.filePaths[0].replace(/\\/g, "/")}`,
          cover: true,
        });
      },
      {
        properties: ["openFile"],
        filters: [
          {
            name: t("settings.images"),
            extensions: ["jpg", "jpeg", "png"],
          },
        ],
      }
    );
  }

  function selectHomeDir() {
    openFileChooser(
      (result) => {
        setHomeDir(result.filePaths[0]);
      },
      { properties: ["openDirectory"] }
    );
  }

  /* -------------------------------------------------------------------------- */
  /*                                  Rendering                                 */
  /* -------------------------------------------------------------------------- */
  return (
    <Container>
      {/* Alerts */}
      {[
        [!playerName, t("errors.playerNameUnset.message")],
        [!homeDir, t("errors.homeDirUnset.message")],
        [!nas, t("errors.nasUnset.message")],
      ]
        .filter(([visible]) => !!visible)
        .map(([, text], index) => (
          <Box key={index} my={1}>
            <Alert severity="error">{text}</Alert>
          </Box>
        ))}

      {/* Theme */}
      <h1>{t("settings.theme")}</h1>
      <Box display={"flex"} flexWrap={"wrap"}>
        {[
          "./funky-lines.png",
          "./gaming.png",
          "./prism.png",
          "./maze.png",
          "./unicorns.png",
        ].map((texture, index) => (
          <PredefinedThemeItem
            key={index}
            src={texture}
            onClick={() => setTheme({ path: texture, cover: false })}
          />
        ))}
        <CustomBackgroundPicker
          hue={backgroundHue}
          onClick={selectCustomBackground}
        >
          <Icon path={mdiImageSearch} size={2} />
        </CustomBackgroundPicker>
      </Box>

      {/* Background Hue Slider */}
      <h1>{t("settings.backgroundHue")}</h1>
      <Slider
        min={0}
        max={360}
        valueLabelDisplay="auto"
        value={backgroundHue}
        onChange={(event, value: number) => setBackgroundHue(value)}
      />

      {/* Environment */}
      <h1>{t("settings.environment")}</h1>
      <Grid container spacing={2}>
        <Grid item xs={3}>
          <FormControl fullWidth>
            <InputLabel id="language-select-label">
              {t("settings.language")}
            </InputLabel>
            <Select
              labelId="language-select-label"
              label={t("settings.language")}
              value={locale}
              onChange={(event) => setLocale(event.target.value)}
            >
              {Object.keys(langs).map((lang, index) => (
                <MenuItem key={index} value={lang}>
                  {t(`langs.${lang}`)}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        </Grid>
        <Grid item xs={6} />
        <Grid item xs={3}>
          <Box display={"flex"} minHeight={"100%"}>
            <Tooltip title={t("settings.debug_explanation")}>
              <FormControlLabel
                label={t("settings.debug")}
                control={
                  <Switch
                    value={debug}
                    onChange={(event, checked) => setDebug(checked)}
                  />
                }
              />
            </Tooltip>
          </Box>
        </Grid>
        <Grid item xs={3}>
          <TextField
            fullWidth
            label={t("settings.playerName")}
            value={playerName}
            error={!playerName}
            onChange={(event) => setPlayerName(event.target.value)}
          />
        </Grid>
        <Grid item xs={4}>
          <Box display={"flex"} minWidth={"100%"} minHeight={"100%"}>
            <TextField
              fullWidth
              label={t("settings.homeDir")}
              value={homeDir}
              disabled={true}
              error={!homeDir}
              onClick={selectHomeDir}
              InputLabelProps={{ disabled: false }}
            />
            <Button onClick={selectHomeDir} disabled={started}>
              <Icon path={mdiDatabaseSearch} size={1} />
            </Button>
          </Box>
        </Grid>
        <Grid item xs={5}>
          <FormControl fullWidth>
            <InputLabel id="nas-select-label" shrink>
              {t("settings.nas")}
            </InputLabel>
            <Select
              labelId="nas-select-label"
              label={t("settings.nas")}
              value={nas}
              onChange={(event) => setNas(event.target.value)}
              error={!nas}
              displayEmpty
              renderValue={(value) =>
                Object.entries(devices).length > 0 ? (
                  value
                ) : (
                  <span>{t("settings.alerts.discovery")}</span>
                )
              }
            >
              {Object.entries(devices).map(([deviceId], index) => (
                <MenuItem key={index} value={deviceId}>
                  {deviceId}
                </MenuItem>
              ))}
            </Select>
            {!online && (
              <FormHelperText>{t("settings.alerts.service")}</FormHelperText>
            )}
          </FormControl>
        </Grid>
      </Grid>
    </Container>
  );
};
